name: Sync Databricks Workspace

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 06:00 UTC
  workflow_dispatch:     # Allows manual trigger

jobs:
  export-databricks:
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Databricks CLI
      run: |
        pip install databricks-cli --upgrade
        databricks configure --host $DATABRICKS_HOST --token $DATABRICKS_TOKEN

    - name: Export Workspace
      run: |
        mkdir -p exported
        databricks workspace export_dir / ./exported --overwrite --format SOURCE

    - name: Export Jobs and Pipelines
      run: |
        mkdir -p exported/configs

        curl -s -X GET -H "Authorization: Bearer $DATABRICKS_TOKEN" \
          $DATABRICKS_HOST/api/2.1/jobs/list \
          -o exported/configs/jobs.json

        curl -s -X GET -H "Authorization: Bearer $DATABRICKS_TOKEN" \
          $DATABRICKS_HOST/api/2.0/pipelines \
          -o exported/configs/pipelines.json

    - name: Commit & Push Changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Automated Databricks sync on $(date)" || echo "No changes to commit"
        git push
